### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by coco66688** [SoCuul/GiveawayBot#1]
(node:66196) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.fields[0].name: Must be 256 or fewer in length.
    at RequestHandler.execute (C:\Users\user\Downloads\GiveawayBot-main\GiveawayBot-main\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\user\Downloads\GiveawayBot-main\GiveawayBot-main\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SoCuul** [comment]
The embed title must be under 256 characters.

**Comment by coco66688** [comment]
> The embed title must be under 256 characters.

????????????????

**Comment by SoCuul** [comment]
@sam920829 Oh sorry. I've fixed the problem. You can just replace your help.js file with the new one, or use the latest version of the repo. Sorry for the inconvenience.
