### ISSUE TITLE
Giveaway removes reactions for the first minute of people reacting

### ISSUE THREAD

**Issue by mkgamingx** [SoCuul/GiveawayBot#3]

**Comment by SoCuul** [comment]
What do you mean it removes reactions. Also, are you using repl.it?

**Comment by mkgamingx** [comment]
when people react, their reactions get removed. i used repl and also vs code

**Comment by mkgamingx** [comment]
nvm i fixed

**Comment by SoCuul** [comment]
Right now repl.it doesn't work and giveaways will randomly get deleted. Please refrain from using it on repl.
