### ISSUE TITLE
config.json reaction

### ISSUE THREAD

**Issue by NotsalgiaHacker** [SoCuul/GiveawayBot#4]
What do I set as "reaction" : " ". I tried the emoji with and without colons (`:tada: and tada`).

I got this error:

`(node:1261) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Emoji
    at RequestHandler.execute (/home/runner/GiveawayBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/GiveawayBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:1261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`

Pls help

**Comment by SoCuul** [comment]
Try the actual Unicode emoji.

Type \🎉 to get the emoji in discord.
