### ISSUE TITLE
No winners

### ISSUE THREAD

**Issue by AlphonsoJuice** [SoCuul/GiveawayBot#5]
When the giveaway ends, this shows- Giveaway cancelled, no valid participations. 
Even though there were a couple of reactions.
Any fix for that?

**Comment by SoCuul** [comment]
Try to ask for support on https://github.com/Androz2091/discord-giveaways

**Comment by JacProsser** [comment]
if you're not going to provide them proper support then realistically they should go [here](https://github.com/ghaku/discord-giveaway-bot)!

**Comment by SoCuul** [comment]
> if you're not going to provide them proper support then realistically they should go [here](https://github.com/ghaku/discord-giveaway-bot)!

Well, I've tested the bot through and through, and I've never been able to get that error. So I have no idea what went wrong.

Also, don't advertise your bot on other peoples repos.

**Comment by JacProsser** [comment]
Well you seem to not know what any of the errors are... I mean the open ones anyway

**Comment by JacProsser** [comment]
First of all i didn't know what was wrong but you find out! I'm only "advertising" as you're not really helping them

**Comment by JacProsser** [comment]
if you make a bot with a package atleast make it so you know about the things they have to ask

**Comment by JacProsser** [comment]
you can gladly delete the comment but update your code! | i'll even open a pr and fix the parseint for you

**Comment by SoCuul** [comment]
Fixed in the newest release
