### ISSUE TITLE
how to fix this in cmd

### ISSUE THREAD

**Issue by Kevinindy2k** [SoCuul/GiveawayBot#6]
(node:15984) UnhandledPromiseRejectionWarning: options.winnerCount is not a positive integer. (val=2)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SoCuul** [comment]
What command are you using? I've never gotten this error.

**Comment by Kevinindy2k** [comment]
create

**Comment by Kevinindy2k** [comment]
![image](https://user-images.githubusercontent.com/45892157/119268362-cb3fe300-bc1c-11eb-968f-2ed1ea442731.png)

**Comment by SoCuul** [comment]
Hmm, try asking in this server: https://discord.gg/6W3vdfMN

**Comment by TotallyNotNico** [comment]
Use parseInt()

**Comment by JacProsser** [comment]
if you're not going to provide them proper support then realistically they should go [here](https://github.com/ghaku/discord-giveaway-bot)

**Comment by SoCuul** [comment]
Fixed in the newest release
